FROM golang:1.19 AS builder

WORKDIR /app

# download deps
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o build

FROM alpine

WORKDIR /app

COPY --from=builder /app/build ./

USER noroot:noroot

CMD ["/build"]