# syntax=docker/dockerfile:1

FROM golang:1.21 

WORKDIR /app

COPY go.mod go.sum ./

# download deps
RUN go mod download

COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./build 

RUN chmod 777 ./build

ENTRYPOINT ["./build"]